DATABASE_URL: "postgresql://encore:password@127.0.0.1:50917/test?sslmode=disable"
BETTER_AUTH_SECRET: "secret"
BETTER_AUTH_URL: "http://localhost:4000"
MAIL_HOST: "smtp.gmail.com"
MAIL_USERNAME: "espositomario996@gmail.com"
MAIL_PASSWORD: "wbgn csbf xqjy pegy"
MAIL_FROM: "espositomario996@gmail.com"
GITHUB_CLIENT_ID: "secret"
GITHUB_CLIENT_SECRET: "secret"
EMAIL_VERIFICATION_CALLBACK_URL: "http://localhost:3000"
NEXT_PUBLIC_BETTER_AUTH_URL: "http://localhost:4000"
NODE_ENV=development