// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({}),
};

import * as HomeRoute from "@/app/page.info";
import * as AuthEmailVerifiedRoute from "@/app/(auth)/email-verified/page.info";
import * as AuthForgotPasswordRoute from "@/app/(auth)/forgot-password/page.info";
import * as AuthResetPasswordRoute from "@/app/(auth)/reset-password/page.info";
import * as AuthSignInRoute from "@/app/(auth)/sign-in/page.info";
import * as AuthSignUpRoute from "@/app/(auth)/sign-up/page.info";
import * as DashboardAdminRoute from "@/app/(dashboard)/admin/page.info";
import * as DashboardUserRoute from "@/app/(dashboard)/user/page.info";
import * as ApiAuthAllRoute from "@/app/api/auth/[...all]/route.info";
import * as PropertiesApiRoute from "@/app/api/properties/route.info";
import * as PropertyApiRoute from "@/app/api/properties/[propertyId]/route.info";
import * as PropertiesRoute from "@/app/properties/page.info";
import * as PropertyDetailRoute from "@/app/properties/[propertyId]/page.info";

export const Home = makeRoute("/", {
  ...defaultInfo,
  ...HomeRoute.Route,
});
export const AuthEmailVerified = makeRoute("/(auth)/email-verified", {
  ...defaultInfo,
  ...AuthEmailVerifiedRoute.Route,
});
export const AuthForgotPassword = makeRoute("/(auth)/forgot-password", {
  ...defaultInfo,
  ...AuthForgotPasswordRoute.Route,
});
export const AuthResetPassword = makeRoute("/(auth)/reset-password", {
  ...defaultInfo,
  ...AuthResetPasswordRoute.Route,
});
export const AuthSignIn = makeRoute("/(auth)/sign-in", {
  ...defaultInfo,
  ...AuthSignInRoute.Route,
});
export const AuthSignUp = makeRoute("/(auth)/sign-up", {
  ...defaultInfo,
  ...AuthSignUpRoute.Route,
});
export const DashboardAdmin = makeRoute("/(dashboard)/admin", {
  ...defaultInfo,
  ...DashboardAdminRoute.Route,
});
export const DashboardUser = makeRoute("/(dashboard)/user", {
  ...defaultInfo,
  ...DashboardUserRoute.Route,
});
export const ApiAuthAll = makeRoute("/api/auth/[...all]", {
  ...defaultInfo,
  ...ApiAuthAllRoute.Route,
});
export const PropertiesApi = makeRoute("/api/properties", {
  ...defaultInfo,
  ...PropertiesApiRoute.Route,
});
export const PropertyApi = makeRoute("/api/properties/[propertyId]", {
  ...defaultInfo,
  ...PropertyApiRoute.Route,
});
export const Properties = makeRoute("/properties", {
  ...defaultInfo,
  ...PropertiesRoute.Route,
});
export const PropertyDetail = makeRoute("/properties/[propertyId]", {
  ...defaultInfo,
  ...PropertyDetailRoute.Route,
});
