import "@/styles/globals.css";
import type { Metadata } from "next";
import ReactQueryProvider from "@/components/providers/ReactQuery";
import { Toaster } from "@/components/ui/sonner";
import env from "@/env";
import { R, RI } from "@/styles/Fonts";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { DashboardLayout as Layout } from "@/components/templates/Layout";
import { ThemeProvider } from "@/components/providers/themeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${R.variable} ${RI.variable} scroll-smooth font-raleway antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReactQueryProvider>
            <Layout>{children}</Layout>
            {env.NODE_ENV === "development" ? <ReactQueryDevtools /> : null}
            <Toaster />
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
