import "@/styles/globals.css";

import type { Metadata } from "next";

import ReactQueryProvider from "@/components/providers/ReactQuery";
import Footer from "@/components/section/Footer";
import Header from "@/components/section/Header";
import { Toaster } from "@/components/ui/sonner";
import env from "@/env";
import { R, RI } from "@/styles/Fonts";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { Layout } from "@/components/templates/Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${R.variable} ${RI.variable} scroll-smooth font-raleway antialiased`}
      >
        <ReactQueryProvider>
          <Layout>{children}</Layout>
          {env.NODE_ENV === "development" ? <ReactQueryDevtools /> : null}
          <Toaster />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
